### ISSUE TITLE
Can EtherWalletKit be used in OC?

### ISSUE THREAD

**Issue by ghost** [SteadyAction/EtherWalletKit#3]
I need to send and receive token, but I didn't find the OC code that I could refer to.

**Comment by SteadyAction** [comment]
@JianRuHong  What OC stands for?

**Comment by ghost** [comment]
> @JianRuHong What OC stands for?

objective-c, 原谅我拙劣的英语....

**Comment by SteadyAction** [comment]
I can't directly help you but ..
Try this: https://stackoverflow.com/questions/37503201/using-swift-library-in-an-objective-c-project
